
import Papa from 'papaparse';
import fs from 'fs'
import sanityClient from '@sanity/client'

// var file = fs.readFileSync('src/csv/Exotic Car Colors Database - Compiled.csv', 'utf8');
// var csv_parsed = Papa.parse(file, {header: true});
// var csv_rows = csv_parsed['data'];



// for (const row in csv_rows){
//     console.log(row)
// const sanityClient = require('@sanity/client')



const CAR_API_URL = 'https://guide-cat-api.sanity-io.now.sh/cats'



const client = sanityClient({
    projectId: 'zlmf9sgs',
    dataset: 'production',
    apiVersion: '2021-08-31',
    token: 'sknpGTYTnk7hrqM4UV2J9VlgKCZikJItdVyGnBbNUfsZ0hdrHhyFQtna2ngw1bKE9Xo819693TlhMIxQ3mLFO2LJKHRej0mKP2bWlDYM9R16NlDJa3KIsMS9t3bFvPlGkKxXDghRNsipUkAIc1z2atsRtqsJRgFDGdMMDGxMzsTTqTKiDI1w', // we need this to get write access
    useCdn: false // We can't use the CDN for writing
  })

const data = [
  {
    "_id": 2,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Arancia Atlas",
    "short_description": "Lamborghini\\'s shiny orange color.",
    "long_description": "Lamborghini's Arancia Atlas is a shiny orange color that pops in the sunlight. It is best based with Nero accents.",
    "hex_color": "#FC9303",
    "hex_text": "#FC9303",
    "rgb_text": "rgb(252,147,3)",
    "cmyk_text": "0, 42, 99, 1",
    "ral_text": "RAL 1033",
    "related_color_1": "Arancio Xanto",
    "related_color_2": "Arancio Bruciato",
    "related_color_3": "Arancio Borealis"
  },
  {
    "_id": 3,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Bianco Isi",
    "short_description": "Lamborghini\\'s shiny white color. ",
    "long_description": "Lamborghini's Bianco Isi is an Aventador specific classy white color, that pairs well with both silver and black accents.",
    "hex_color": "#C0CBCD",
    "hex_text": "#C0CBCD",
    "rgb_text": "rgb(192,203,205)",
    "cmyk_text": "6, 1, 0, 20",
    "ral_text": "RAL 7035",
    "related_color_1": "Bianco Avorio",
    "related_color_2": "Pearl White",
    "related_color_3": "Bianco Asopo"
  },
  {
    "_id": 4,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Nila",
    "short_description": "Lamborghini\\'s shiny blue color. ",
    "long_description": "Lamborghini's Blu Nila was popularized on the Aventador, and is a shiny blue that can be paired with Nero, silver, or Rosso accents.",
    "hex_color": "#017EF4",
    "hex_text": "#017EF4",
    "rgb_text": "rgb(1,126,244)\n",
    "cmyk_text": "100, 48, 0, 4",
    "ral_text": "RAL 5014",
    "related_color_1": "Blu Le Mans",
    "related_color_2": "Blu Caelum",
    "related_color_3": "Blu Fontus"
  },
  {
    "_id": 5,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Nero Aldebaran",
    "short_description": "Lamborghini\\'s shiny black color. ",
    "long_description": "Lamborghini’s Nero Aldebaran is classic solid black that is specific only to the Avendator. The stealth look conceals itself well if needed, but also pops in the sunlight. Nero Aldebaran pairs well with additional accent colors such as Giallo, Rosso, or Blu accents.",
    "hex_color": "#0D1015",
    "hex_text": "#0D1015",
    "rgb_text": "rgb(13,16,21)\n",
    "cmyk_text": "38, 24, 0, 92",
    "ral_text": "RAL 9005",
    "related_color_1": "Nero Granatus",
    "related_color_2": "Nero Pegaso",
    "related_color_3": "Nero Nemesis"
  },
  {
    "_id": 6,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Giallo Orion",
    "short_description": "Lamborghini\\'s shiny yellow color.",
    "long_description": "Lamborghini's Giallo Orion was first seen on the Murcielago, and has since transitioned into the Aventador's shiny yellow color. It is best paired with Nero, or Rosso accents.",
    "hex_color": "#FEA700",
    "hex_text": "#FEA700",
    "rgb_text": "rgb(254,167,0)",
    "cmyk_text": "0, 34, 100, 0",
    "ral_text": "RAL 1003",
    "related_color_1": "Giallo Inti",
    "related_color_2": "Giallo Auge",
    "related_color_3": "Giallo Tenerife"
  },
  {
    "_id": 7,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Rosso Mars",
    "short_description": "Lamborghini\\'s shiny red color.",
    "long_description": "Lamborghini's Rosso Mars is a common shiny red option for the Aventador, Huracan, and Urus alike. This color pops well with Giallo or Nero acents and shows the true Lamborghini ethos. ",
    "hex_color": "#D40000",
    "hex_text": "#D40000",
    "rgb_text": "rgb(212,0,0)",
    "cmyk_text": "0, 100, 100, 17",
    "ral_text": "RAL 3028",
    "related_color_1": "Rosso Efesto",
    "related_color_2": "Rosso Efesto",
    "related_color_3": "Rosso Bia"
  },
  {
    "_id": 8,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Mantis",
    "short_description": "Lamborghini\\'s shiny green color. ",
    "long_description": "Lamborghini's Verde Mantis is a classic shiny green option primarily for the Huracan. This color represents Lamborghini's bright and bold ethos perfectly, and will guarantee you road precense. ",
    "hex_color": "#7DC23B",
    "hex_text": "#7DC23B",
    "rgb_text": "rgb(125,194,59)\n",
    "cmyk_text": "36, 0, 70, 24",
    "ral_text": "RAL 6018",
    "related_color_1": "Verde Selvans",
    "related_color_2": "Verde Gea Lucido",
    "related_color_3": "Verde Citrea"
  },
  {
    "_id": 9,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Arancio Xanto",
    "short_description": "Lamborghini\\'s sportiva orange color.",
    "long_description": "Lamborghini's Arancio Xanto is a fire orange color that is seen on both the Huracan and Aventador. It is known to pop in the sun, and looks stunning with Nero accents.",
    "hex_color": "#E64A37",
    "hex_text": "#E64A37",
    "rgb_text": "rgb(230,74,55)\n",
    "cmyk_text": "0, 68, 76, 10",
    "ral_text": "RAL 2012",
    "related_color_1": "Arancia Atlas",
    "related_color_2": "Arancio Borealis",
    "related_color_3": "Arancio Bruciato"
  },
  {
    "_id": 10,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Bianco Asopo",
    "short_description": "Lamborghini\\'s sportiva white color.",
    "long_description": "Lamborghini's Bianco Asopo is a classic white that is seen primarily as a color option for the Aventador SVJ. It is a very versatile paint color, and can be paired with different accent types.",
    "hex_color": "#F3FAFD",
    "hex_text": "#F3FAFD",
    "rgb_text": "rgb(243,250,253)\n",
    "cmyk_text": "4, 1, 0, 1",
    "ral_text": "RAL 9003",
    "related_color_1": "Bianco Isi",
    "related_color_2": "Bianco Comes",
    "related_color_3": "Bianco Monocerus"
  },
  {
    "_id": 11,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Nethuns",
    "short_description": "Lamborghini\\'s sportiva blue color.",
    "long_description": "Lamborghini's Blu Nethuns is a striking blue that pairs well with stealth Nero accents. It is a common Huracan option, but is also seen on Aventador models.",
    "hex_color": "#1336EA",
    "hex_text": "#1336EA",
    "rgb_text": "rgb(19,54,234)",
    "cmyk_text": "92, 77, 0, 8",
    "ral_text": "RAL 5000",
    "related_color_1": "Blu Uranus",
    "related_color_2": "Blu Caelum",
    "related_color_3": "Blu Le Mans"
  },
  {
    "_id": 12,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Telesto",
    "short_description": "Lamborghini\\'s sportiva grey color.",
    "long_description": "Grigio Telesto creates a beautiful stealth look on Lamborghinis. It is seen with Nero, and Bronze accents primarily to add to the stealth look.",
    "hex_color": "#7692A5",
    "hex_text": "#7692A5",
    "rgb_text": "rgb(118,146,165)\n",
    "cmyk_text": "28, 12, 0, 35",
    "ral_text": "RAL 5024",
    "related_color_1": "Grigio Antares",
    "related_color_2": "Grigio Hati",
    "related_color_3": "Grigio Lynx"
  },
  {
    "_id": 13,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Selvans",
    "short_description": "Lamborghini\\'s sportiva green color. ",
    "long_description": "Verde Selvans is a stunning bright green color primarily seen on the Huracan. It fits Lamborghini's ethos perfectly, and shimmers in the sun. It is best paired with Nero accents.",
    "hex_color": "#67C52F",
    "hex_text": "#67C52F",
    "rgb_text": "rgb(103,197,47)\n",
    "cmyk_text": "48, 0, 76, 23",
    "ral_text": "RAL 6038",
    "related_color_1": "Verde Mantis",
    "related_color_2": "Verde Ithaca",
    "related_color_3": "Verde Ermes"
  },
  {
    "_id": 14,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Viola Pasifae",
    "short_description": "Lamborghini\\'s sportiva purple color.",
    "long_description": "Viola Pasifae is seen on both the Aventador and Huracan models. The color works well with lighter silver and white accents, but also looks stunning and stealthy with black accents. ",
    "hex_color": "#6B0686",
    "hex_text": "#6B0686",
    "rgb_text": "rgb(107,6,134)\n",
    "cmyk_text": "20, 96, 0, 47",
    "ral_text": "RAL 4006",
    "related_color_1": "Viola 30",
    "related_color_2": "Viola Aletheia",
    "related_color_3": "Lantana Purple"
  },
  {
    "_id": 15,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Arancio Bruciato",
    "short_description": "Lamborghini\\'s contemporary orange color.",
    "long_description": "Arancio Bruiato is an orange that has been spotted on the new and exclusive Sian, but can be optioned on all cars. It pairs well with Giallo or Nero accents, and has an darker shade than other Oranges. ",
    "hex_color": "#D74C10",
    "hex_text": "#D74C10",
    "rgb_text": "rgb(215,76,16)\n",
    "cmyk_text": "0, 65, 93, 16",
    "ral_text": "RAL 2009",
    "related_color_1": "Arancio Argos",
    "related_color_2": "Arancio Xanto",
    "related_color_3": "Rosso Arancio"
  },
  {
    "_id": 16,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Balloon White",
    "short_description": "Lamborghini\\'s contemporary white color.",
    "long_description": "Balloon white is one of the classiest Aventador colors that can be optioned because of its subtle grey undertone. The color is often seen on Aventadors, and can be paired with virtually any accents. ",
    "hex_color": "#E8E8E8",
    "hex_text": "#E8E8E8",
    "rgb_text": "rgb(232,232,232)\n",
    "cmyk_text": "0, 0, 0, 9",
    "ral_text": "RAL 9003",
    "related_color_1": "Bianco Isi",
    "related_color_2": "Bianco Avus",
    "related_color_3": "Pearl White"
  },
  {
    "_id": 17,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Aegir",
    "short_description": "Lamborghini\\'s contemporary blue color.",
    "long_description": "Blu Aegir's almost metallic finish is meant to pop in the sun. It is classy, but bold at the same time, and is seen on both Aventadors and Huracans. It's bright nature often pairs well with silver accents.",
    "hex_color": "#2CAEFE",
    "hex_text": "#2CAEFE",
    "rgb_text": "rgb(44,174,254)\n",
    "cmyk_text": "83, 31, 0, 0",
    "ral_text": "RAL 5024",
    "related_color_1": "Blu Notte",
    "related_color_2": "Blu Uranus",
    "related_color_3": "Blu Le Mans"
  },
  {
    "_id": 18,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Bronzo Zante",
    "short_description": "Lamborghini\\'s contemporary bronze color.",
    "long_description": "Bronzo Zante, seen primarily on Aventadors offers the stealth Lamborghini style with a bit of pop in the sun. It is a stunning blend of everything that the Lamborghini brand stands for, and pairs well with Nero accents. ",
    "hex_color": "#B08D57",
    "hex_text": "#B08D57",
    "rgb_text": "rgb(176,141,87)\n",
    "cmyk_text": "0, 20, 51, 31",
    "ral_text": "RAL 1024",
    "related_color_1": "Oros Elios",
    "related_color_2": "Verde Gea Lucido",
    "related_color_3": "Nero Granatus"
  },
  {
    "_id": 19,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Nero Granatus",
    "short_description": "Lamborghini\\'s contemporary black color.",
    "long_description": "Nero Granatus is a special Lamborghini color; black from afar, but once you get up close or go in the sun, the color shifts to an almost metallic marroon color. It is often optioned with either black or silver accents. ",
    "hex_color": "#92555D",
    "hex_text": "#92555D",
    "rgb_text": "rgb(146,85,93)\n",
    "cmyk_text": "0, 42, 36, 43",
    "ral_text": "RAL 4002",
    "related_color_1": "Nero Helene",
    "related_color_2": "Nero Nemesis",
    "related_color_3": "Nero Pegaso"
  },
  {
    "_id": 20,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Rosso Efesto",
    "short_description": "Lamborghini\\'s contemporary red color.",
    "long_description": "Rosso Efesto is a bright cherry red color that is primarily seen on the Aventadors. It has been optioned with Bronze, black and silver accents and is very versatile.",
    "hex_color": "#F4221F",
    "hex_text": "#F4221F",
    "rgb_text": "rgb(244,34,31)\n",
    "cmyk_text": "0, 86, 87, 4",
    "ral_text": "RAL 3028",
    "related_color_1": "Rosso Mars",
    "related_color_2": "Rosso Arancio",
    "related_color_3": "Rosso Bia"
  },
  {
    "_id": 21,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Gea Lucido",
    "short_description": "Lamborghini\\'s contemporary green color.",
    "long_description": "Verde Gea Lucido was first seen when the Lamborghini Sian was unveiled. It is a classic green with matte accents that looks stunning with bronze accents.",
    "hex_color": "#8B8970",
    "hex_text": "#8B8970",
    "rgb_text": "rgb(139,137,112)\n",
    "cmyk_text": "0, 1, 19, 45",
    "ral_text": "RAL 7034",
    "related_color_1": "Bronzo Zante",
    "related_color_2": "Verde Citrea",
    "related_color_3": "Verde Metallic"
  },
  {
    "_id": 22,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Bianco Comes",
    "short_description": "Lamborghini\\'s pearl white color.",
    "long_description": "Bianco Comes is a classic Lamborghini color that is commonly optioned on both Huracan and Aventador models. It is a versatile pearly white that can look stunning with any accent.",
    "hex_color": "#FBFBFB",
    "hex_text": "#FBFBFB",
    "rgb_text": "rgb(251,251,251)\n",
    "cmyk_text": "0, 0, 0, 2",
    "ral_text": "RAL 9016",
    "related_color_1": "Bianco Asopo",
    "related_color_2": "Bianco Monocerus",
    "related_color_3": "Bianco Isi"
  },
  {
    "_id": 23,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Cepheus",
    "short_description": "Lamborghini\\'s pearl blue color.",
    "long_description": "Blu Cepheus is seen on all Lamborghini models: Huracans, Aventadors, Centenarios and even classics like the Murcialago. The beautiful bright blue pops in the sun, and pairs well with both Black and Silver accents. ",
    "hex_color": "#39BFFE",
    "hex_text": "#39BFFE",
    "rgb_text": "rgb(57,191,254)\n",
    "cmyk_text": "78, 25, 0, 0",
    "ral_text": "RAL 5024",
    "related_color_1": "Blu Uranus",
    "related_color_2": "Blu Aegir",
    "related_color_3": "Blu Notte"
  },
  {
    "_id": 24,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Uranus",
    "short_description": "Lamborghini's pearl ocean color.",
    "long_description": "Blu Uranus was debuted on the Lamborghini Sian, and has a teal, ocean like color. This color is sure to pop in the sun, and is also commonly paired with bronze accents. ",
    "hex_color": "#0177A4",
    "hex_text": "#0177A4",
    "rgb_text": "rgb(1,119,164)",
    "cmyk_text": "99, 27, 0, 36",
    "ral_text": "RAL 5015",
    "related_color_1": "Blu Cepheus",
    "related_color_2": "Blu Nethuns",
    "related_color_3": "Blu Eleos"
  },
  {
    "_id": 25,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Oros Elios",
    "short_description": "Lamborghini's pearl bronze color.",
    "long_description": "Oros Elios's yellow gold like color that looks beautiful in the sun. This Arabian color style looks beautiful in both black and silver accents. ",
    "hex_color": "#B88B60",
    "hex_text": "#B88B60",
    "rgb_text": "rgb(184,139,96)",
    "cmyk_text": "0, 24, 48, 28",
    "ral_text": "RAL 1011",
    "related_color_1": "Bronzo Zante",
    "related_color_2": "Verde Gea Lucido",
    "related_color_3": "Blu Cepheus"
  },
  {
    "_id": 26,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Citrea",
    "short_description": "Lamborghini's pearl green color.",
    "long_description": "Verde Citrea is a Lamborghini colors option for both Huracan and Aventador models, and is a bright battery green that looks similar to Porsche's Acid Green.",
    "hex_color": "#9AF95D",
    "hex_text": "#9AF95D",
    "rgb_text": "rgb(154,249,93)",
    "cmyk_text": "38, 0, 63, 2",
    "ral_text": "RAL 6019",
    "related_color_1": "Verde Metallic",
    "related_color_2": "Verde Gea Lucido",
    "related_color_3": "Verde Mantis"
  },
  {
    "_id": 27,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Notte",
    "short_description": "Lamborghini's classic blue color.",
    "long_description": "Blu Notte is a slightly darker blue Aventador color that is very versatile, paring well with Nero and Silver accents.",
    "hex_color": "#212E58",
    "hex_text": "#212E58",
    "rgb_text": "rgb(33,46,88)\n",
    "cmyk_text": "63, 48, 0, 65",
    "ral_text": "RAL 5022",
    "related_color_1": "Blu Nethuns",
    "related_color_2": "Blu Nereid",
    "related_color_3": "Blu Astraeus"
  },
  {
    "_id": 28,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Rosso Arancio",
    "short_description": "Lamborghini's classic red color.",
    "long_description": "Rosso Arancio is a fire red paint color that looks slightly orange. It pops in the sun, and is paired well with Nero and Orange accents.",
    "hex_color": "#DD3D0D",
    "hex_text": "#DD3D0D",
    "rgb_text": "rgb(221,61,13)\n",
    "cmyk_text": "0, 72, 94, 13",
    "ral_text": "RAL 2009",
    "related_color_1": "Rosso Bia",
    "related_color_2": "Rosso Efesto",
    "related_color_3": "Rosso Mars"
  },
  {
    "_id": 29,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Metallic",
    "short_description": "Lamborghini's classic british racing green color.",
    "long_description": "Verde Metallic looks like a metallic version of British Racing Green, making it pop more in the sunlight. It looks stunning with Bronze accents.",
    "hex_color": "#8FC028",
    "hex_text": "#8FC028",
    "rgb_text": "rgb(143,192,40)\n",
    "cmyk_text": "26, 0, 79, 25",
    "ral_text": "RAL 6018",
    "related_color_1": "Verde Citrea",
    "related_color_2": "Verde Gea Lucido",
    "related_color_3": "Verde Ermes"
  },
  {
    "_id": 30,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Scandal",
    "short_description": "Lamborghini's classic green color.",
    "long_description": "Verde Scandal is an incredibly bright green offered for Huracan and Lamborghini models. It shines in the light, and pairs well with subtle black accents.",
    "hex_color": "#84E12E",
    "hex_text": "#84E12E",
    "rgb_text": "rgb(132,225,46)",
    "cmyk_text": "41, 0, 80, 12",
    "ral_text": "RAL 6038",
    "related_color_1": "Verde Metallic",
    "related_color_2": "Verde Gea Lucido",
    "related_color_3": "Verde Citrea"
  },
  {
    "_id": 31,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Viola 30",
    "short_description": "Lamborghini's classic purple color. ",
    "long_description": "Viola 30 is seen on both the Huaracan and Aventador, and is a metallic purple color, that shimmers in the sunlight. It works well with Bronze, black and silver accents. ",
    "hex_color": "#B27CB6",
    "hex_text": "#B27CB6",
    "rgb_text": "rgb(178,124,182)\n",
    "cmyk_text": "2, 32, 0, 29",
    "ral_text": "RAL 4003",
    "related_color_1": "Viola Pasifae",
    "related_color_2": "Viola Aletheia",
    "related_color_3": "Lantana Purple"
  },
  {
    "_id": 32,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Arancio Argos",
    "short_description": "Lamborghini's Ad Personam fire red color.",
    "long_description": "Arancio Argos, primarily seen on the Aventadors, is a bold red with a hint of orange undertones. Black accents make for a stunning combination with this color.",
    "hex_color": "#FB6445",
    "hex_text": "#FB6445",
    "rgb_text": "rgb(251,100,69)\n",
    "cmyk_text": "0, 60, 73, 2",
    "ral_text": "RAL 3024",
    "related_color_1": "Rosso Arancio",
    "related_color_2": "Arancio Borealis",
    "related_color_3": "Arancia Atlas"
  },
  {
    "_id": 33,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Arancio Borealis",
    "short_description": "Lamborghini's Ad Personam orange color.",
    "long_description": "Arancio Borealis' is a bright sunset orange commonly viewed on the Huracan Performante. Silver and black accents pair the best with this color to bring out the shine of the car.",
    "hex_color": "#FBA400",
    "hex_text": "#FBA400",
    "rgb_text": "rgb(251,164,0)\n",
    "cmyk_text": "0, 35, 100, 2",
    "ral_text": "RAL 1003",
    "related_color_1": "Arancio Argos",
    "related_color_2": "Arancia Atlas",
    "related_color_3": "Arancio Bruciato"
  },
  {
    "_id": 34,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Azzurro Thetys",
    "short_description": "Lamborghini's Ad Personam light blue color.",
    "long_description": "Azzurro Thetys creates a metallic shine with its frosty blue hue and was popularized on the Aventator. Silver accents bring out the sleek nature of the color, whereas black accents draw out a more stealthier look. ",
    "hex_color": "#8CA0B8",
    "hex_text": "#8CA0B8",
    "rgb_text": "rgb(140,160,184)",
    "cmyk_text": "24, 13, 0, 28",
    "ral_text": "RAL 7001",
    "related_color_1": "Blu Eleos",
    "related_color_2": "Blu Glauco",
    "related_color_3": "Blu Le Mans"
  },
  {
    "_id": 35,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Bianco Monocerus",
    "short_description": "Lamborghini's Ad Personam white color.",
    "long_description": "Bianco Monocerus is seen on both the Huracan Performante and Urus. This pearlescent white radiates elegance and is often paired with bold red accents, however its versatile nature makes different accent types possible.",
    "hex_color": "#EDEDED",
    "hex_text": "#EDEDED",
    "rgb_text": "rgb(237,237,237)",
    "cmyk_text": "0, 0, 0, 7",
    "ral_text": "RAL 9003",
    "related_color_1": "Bianco Isi",
    "related_color_2": "Bianco Asopo",
    "related_color_3": "Bianco Comes"
  },
  {
    "_id": 36,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Astraeus",
    "short_description": "Lamborghini's Ad Personam deep blue color.",
    "long_description": "Blue Astraeus is a deep and rich blue with violet undertones that has been seen primarily on the Urus. It looks stunning with yellow, black or silver accents.",
    "hex_color": "#00024C",
    "hex_text": "#00024C",
    "rgb_text": "rgb(0,2,76)",
    "cmyk_text": "100, 97, 0, 70",
    "ral_text": "RAL 5022",
    "related_color_1": "Blu Nereid",
    "related_color_2": "Blu Caelum",
    "related_color_3": "Blu Eleos"
  },
  {
    "_id": 37,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Caelum",
    "short_description": "Lamborghini's Ad Personam royal blue color.",
    "long_description": "Blu Caelum is an edgy royal blue found on both the Avendator and Huracan. It works well with Giallo or silver accents to give off a radiant finish.",
    "hex_color": "#054AE3",
    "hex_text": "#054AE3",
    "rgb_text": "rgb(5,74,227)",
    "cmyk_text": "98, 67, 0, 11",
    "ral_text": "RAL 5023",
    "related_color_1": "Blu Astraeus",
    "related_color_2": "Blu Glauco",
    "related_color_3": "Blu Le Mans"
  },
  {
    "_id": 38,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Eleos",
    "short_description": "Lamborghini's Ad Personam shiny blue color.",
    "long_description": "Blue Eleos, commonly found on the Urus and Huracan, is shiny blue at a slightly lighter hue than royal. Nero or Grigio accents compliment this electric blue very nicely.",
    "hex_color": "#418DD8",
    "hex_text": "#418DD8",
    "rgb_text": "rgb(65,141,216)\n",
    "cmyk_text": "70, 35, 0, 15",
    "ral_text": "RAL 5024",
    "related_color_1": "Blu Le Mans",
    "related_color_2": "Blu Le Mans",
    "related_color_3": "Blu Nereid"
  },
  {
    "_id": 39,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Fontus",
    "short_description": "Lamborghini's Ad Personam dark blue color. ",
    "long_description": "Blue Fontus creates a stunningly stealthy look with its deep navy blue hue. Seen primarily on Gallordos, this color pairs well with primarily silver but also gold accents. ",
    "hex_color": "#313247",
    "hex_text": "#313247",
    "rgb_text": "rgb(49,50,71)\n",
    "cmyk_text": "31, 30, 0, 72",
    "ral_text": "RAL 5013",
    "related_color_1": "Blu Caelum",
    "related_color_2": "Blu Eleos",
    "related_color_3": "Blu Nila"
  },
  {
    "_id": 40,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Glauco",
    "short_description": "Lamborghini's Ad Personam teal color.",
    "long_description": "Blue Glauco is a shiny, electric teal that makes for an exotic look. This confident and eye-catching color can be found on both Aventadors and Huracans. Silver and black accents best compliement this bold color.",
    "hex_color": "#08C7E3",
    "hex_text": "#08C7E3",
    "rgb_text": "rgb(8,199,227)\n",
    "cmyk_text": "96, 12, 0, 11",
    "ral_text": "RAL 6027",
    "related_color_1": "Blu Eleos",
    "related_color_2": "Blu Nereid",
    "related_color_3": "Blu Le Mans"
  },
  {
    "_id": 41,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Le Mans",
    "short_description": "Lamborghini's Ad Personam bright blue color.",
    "long_description": "Blu Le Mans' bright, electric blue can be found on both Aventadors and Huracans. Red and black accents work well together to accentuate the color's beauty to give it a powerful look.",
    "hex_color": "#0690FF",
    "hex_text": "#0690FF",
    "rgb_text": "rgb(6,144,255)\n",
    "cmyk_text": "98, 44, 0, 0",
    "ral_text": "RAL 5024",
    "related_color_1": "Blu Nereid",
    "related_color_2": "Blu Astraeus",
    "related_color_3": "Blu Eleos"
  },
  {
    "_id": 42,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Blu Nereid",
    "short_description": "Lamborghini's Ad Personam metallic blue color. ",
    "long_description": "Blue Nereid is a shiny metallic blue with blended violet undertones that give the Aventadors a tranformative look. Giallo accents compliment this color and enhance its exotic look.",
    "hex_color": "#2539BC",
    "hex_text": "#2539BC",
    "rgb_text": "rgb(37,57,188)\n",
    "cmyk_text": "80, 70, 0, 26",
    "ral_text": "RAL 5002",
    "related_color_1": "Blu Nila",
    "related_color_2": "Blu Glauco",
    "related_color_3": "Blu Le Mans"
  },
  {
    "_id": 43,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Giallo Auge",
    "short_description": "Lamborghini's Ad Personam yellow color. ",
    "long_description": "Giallo Auge was introduced on the Urus as a special launch color. This classic yellow brings a confident pop of color to the car and is best accentuated by Nero or silver accents. ",
    "hex_color": "#FEBE05",
    "hex_text": "#FEBE05",
    "rgb_text": "rgb(254,190,5)\n",
    "cmyk_text": "0, 25, 98, 0",
    "ral_text": "RAL 1023",
    "related_color_1": "Giallo Evros",
    "related_color_2": "Giallo Inti",
    "related_color_3": "Giallo Inti"
  },
  {
    "_id": 44,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Giallo Evros",
    "short_description": "Lamborghini's Ad Personam dark yellow color. ",
    "long_description": "Giallo Evros is a russet yellow that gives a metallic-like finish to the Aventadors. Black and silver accents pair best with this sunset yellow.",
    "hex_color": "#E28F01",
    "hex_text": "#E28F01",
    "rgb_text": "rgb(226,143,1)",
    "cmyk_text": "0, 37, 100, 11",
    "ral_text": "RAL 1006",
    "related_color_1": "Giallo Auge",
    "related_color_2": "Giallo Spica",
    "related_color_3": "Giallo Tenerife"
  },
  {
    "_id": 45,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Giallo Inti",
    "short_description": "Lamborghini's Ad Personam bright yellow color. ",
    "long_description": "Giallo Inti found on Huracans is a bright yellow that shines in the sun. This raidant color popularly pairs with Nero accents and occasionally Grigio.",
    "hex_color": "#FED136",
    "hex_text": "#FED136",
    "rgb_text": "rgb(254,209,54)",
    "cmyk_text": "0, 18, 79, 0",
    "ral_text": "RAL 1018",
    "related_color_1": "Giallo Orion",
    "related_color_2": "Giallo Tenerife",
    "related_color_3": "Giallo Spica"
  },
  {
    "_id": 46,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Giallo Spica",
    "short_description": "Lamborghini's Ad Personam pearl yellow color.",
    "long_description": "Giallo Spica creates an electric look with its pearlescent yellow. Found on both Huracans and Aventadors, this color combines well with Nero accents to give off a stealthy and powerful finish.",
    "hex_color": "#F2C32F",
    "hex_text": "#F2C32F",
    "rgb_text": "rgb(242,195,47)",
    "cmyk_text": "0, 19, 81, 5",
    "ral_text": "RAL 1018",
    "related_color_1": "Giallo Inti",
    "related_color_2": "Giallo Auge",
    "related_color_3": "Giallo Tenerife"
  },
  {
    "_id": 47,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Giallo Tenerife",
    "short_description": "Lamborghini's Ad Personam pale yellow color.",
    "long_description": "Giallo Tenerife is a pale, bright yellow that can be found on both the Huracan and Aventador. This colors looks beautiful with black and silver accents.",
    "hex_color": "#F2F427",
    "hex_text": "#F2F427",
    "rgb_text": "rgb(242,244,39)\n",
    "cmyk_text": "1, 0, 84, 4",
    "ral_text": "RAL 1016",
    "related_color_1": "Giallo Evros",
    "related_color_2": "Giallo Orion",
    "related_color_3": "Giallo Auge"
  },
  {
    "_id": 48,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Antares",
    "short_description": "Lamborghini's Ad Personam metallic grey color. ",
    "long_description": "Grigio Antares is a light metallic grey found on the Aventadors. Black and red accents expertly tie the whole look together and give the car a stunning finish.",
    "hex_color": "#A6ADB7",
    "hex_text": "#A6ADB7",
    "rgb_text": "rgb(166,173,183)",
    "cmyk_text": "9, 5, 0, 28",
    "ral_text": "RAL 7040",
    "related_color_1": "Grigio Ater",
    "related_color_2": "Grigio Keres",
    "related_color_3": "Grigio Liqueo"
  },
  {
    "_id": 49,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Ater",
    "short_description": "Lamborghini's Ad Personam  dark grey color.",
    "long_description": "Grigio Ater, found primarily on the Aventador, creates a sleek and stealthy look with its dark grey hue. This beautiful color accentuates the curves of the car well and pairs strongly with red and black accents.",
    "hex_color": "#727274",
    "hex_text": "#727274",
    "rgb_text": "rgb(114,114,116)",
    "cmyk_text": "2, 2, 0, 55",
    "ral_text": "RAL 9023",
    "related_color_1": "Grigio Keres",
    "related_color_2": "Grigio Telesto",
    "related_color_3": "Grigio Nimbus"
  },
  {
    "_id": 50,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Estoque",
    "short_description": "Lamborghini's Ad Personam  metallic grey color.",
    "long_description": "Grigio Estoque is a deep metallic grey that gives the Aventadors a sharp and polished look. This color looks stunning with Giallo accents that bring a pop of color as well as Nero accents that draw out the powerful nature of this color. ",
    "hex_color": "#ACACAE",
    "hex_text": "#ACACAE",
    "rgb_text": "rgb(172,172,174)",
    "cmyk_text": "1, 1, 0, 32",
    "ral_text": "RAL 9006",
    "related_color_1": "Grigio Nimbus",
    "related_color_2": "Grigio Lynx",
    "related_color_3": "Grigio Keres"
  },
  {
    "_id": 51,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Hati",
    "short_description": "Lamborghini's Ad Personam light grey color.",
    "long_description": "Grigio Hati is a light grey that brings a pearlescent look to the Huracans and Aventadors. Red and black accents highlight the radiant nature of this color and emphasize its beauty.",
    "hex_color": "#C7D7E7",
    "hex_text": "#C7D7E7",
    "rgb_text": "rgb(199,215,231)",
    "cmyk_text": "14, 7, 0, 9",
    "ral_text": "RAL 7047",
    "related_color_1": "Grigio Antares",
    "related_color_2": "Grigio Liqueo",
    "related_color_3": "Grigio Keres"
  },
  {
    "_id": 52,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Keres",
    "short_description": "Lamborghini's Ad Personam metallic grey color.",
    "long_description": "Grigio Keres is seen primarily to the Urus and is a dark graphite grey with a metallic finish. Interestingly, the versatile nature of this color allows for any matter of accent to be paired with it including bold colors like lime green and orange.",
    "hex_color": "#6F6F6F",
    "hex_text": "#6F6F6F",
    "rgb_text": "rgb(111,111,111)",
    "cmyk_text": "0, 0, 0, 56",
    "ral_text": "RAL 7005",
    "related_color_1": "Grigio Lynx",
    "related_color_2": "Grigio Estoque",
    "related_color_3": "Grigio Nimbus"
  },
  {
    "_id": 53,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Liqueo",
    "short_description": "Lamborghini's Ad Personam light metallic grey color.",
    "long_description": "Grigio Liqueo is a light metallic grey with beautiful warm undertones and is commonly found on Aventadors. To accentuate its sleek nature, this color is often complimented by red and black accents.",
    "hex_color": "#85898D",
    "hex_text": "#85898D",
    "rgb_text": "rgb(133,137,141)",
    "cmyk_text": "6, 3, 0, 45",
    "ral_text": "RAL 7046",
    "related_color_1": "Grigio Hati",
    "related_color_2": "Grigio Antares",
    "related_color_3": "Grigio Estoque"
  },
  {
    "_id": 54,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Lynx",
    "short_description": "Lamborghini's Ad Personam grey color.",
    "long_description": "Grigio Lynx is a deep and poweful grey that gives the Huracan a stealthy look. The versatile nature of this color allows for any accent but bright colors like red, yellow and orange compliment it beautifully.",
    "hex_color": "#707176",
    "hex_text": "#707176",
    "rgb_text": "rgb(112,113,118)",
    "cmyk_text": "5, 4, 0, 54",
    "ral_text": "RAL 9023",
    "related_color_1": "Grigio Nimbus",
    "related_color_2": "Grigio Keres",
    "related_color_3": "Grigio Lynx"
  },
  {
    "_id": 55,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Grigio Nimbus",
    "short_description": "Lamborghini's Ad Personam bright light grey color.",
    "long_description": "Grigio Nimbus can be found on both the Huracan and Urus and is a bright, light grey color. Bright accents like yellow and red highlight the beauty of this color well.",
    "hex_color": "#6B7278",
    "hex_text": "#6B7278",
    "rgb_text": "rgb(107,114,120)",
    "cmyk_text": "11, 5, 0, 53",
    "ral_text": "RAL 7031",
    "related_color_1": "Grigio Liqueo",
    "related_color_2": "Grigio Estoque",
    "related_color_3": "Grigio Hati"
  },
  {
    "_id": 56,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Nero Helene",
    "short_description": "Lamborghini's Ad Personam black color.",
    "long_description": "Nero Helene is a classic black that gives the car a powerful look. The Huracan and Urus display this color with red or yellow accents that bring a beautiful pop of color to this stealthy look.",
    "hex_color": "#151618",
    "hex_text": "#151618",
    "rgb_text": "rgb(21,22,24)",
    "cmyk_text": "13, 8, 0, 91",
    "ral_text": "RAL 9005",
    "related_color_1": "Nero Aldebaran",
    "related_color_2": "Nero Noctis",
    "related_color_3": "Nero Nemesis"
  },
  {
    "_id": 57,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Nero Noctis",
    "short_description": "Lamborghini's Ad Personam metallic black color.",
    "long_description": "Nero Noctis is a shiny, metallic black common to the Huracan and Urus. This color is sleek and polished, and pairs well with red or orange accents that offer a beautiful contrast.",
    "hex_color": "#292927",
    "hex_text": "#292927",
    "rgb_text": "rgb(41,41,39)",
    "cmyk_text": "0, 0, 5, 84",
    "ral_text": "RAL 9017",
    "related_color_1": "Nero Granatus",
    "related_color_2": "Nero Aldebaran",
    "related_color_3": "Nero Pegaso"
  },
  {
    "_id": 58,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Nero Pegaso",
    "short_description": "Lamborghini's Ad Personam dark black color.",
    "long_description": "Nero Pegaso can be found on the Aventador and is a deep and rich dark black color. Arancio or red accents contrast well with this color.",
    "hex_color": "#080D10",
    "hex_text": "#080D10",
    "rgb_text": "rgb(8,13,16)",
    "cmyk_text": "50, 19, 0, 94",
    "ral_text": "RAL 9005",
    "related_color_1": "Nero Nemesis",
    "related_color_2": "Nero Helene",
    "related_color_3": "Nero Aldebaran"
  },
  {
    "_id": 59,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Nero Nemesis",
    "short_description": "Lamborghini's Ad Personam matte black color.",
    "long_description": "Nero Nemesis is a beautiful matte black color with a subtle hint of grey undertones. This color appears on both Huracans and Aventadors, and is complemented well with red or orange accents.",
    "hex_color": "#312F30",
    "hex_text": "#312F30",
    "rgb_text": "rgb(49,47,48)",
    "cmyk_text": "0, 4, 2, 81",
    "ral_text": "RAL 9004",
    "related_color_1": "Nero Pegaso",
    "related_color_2": "Nero Noctis",
    "related_color_3": "Nero Helene"
  },
  {
    "_id": 60,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Rosso Bia",
    "short_description": "Lamborghini's Ad Personam cherry red color.",
    "long_description": "Rosso Bia is a bold, cherry red found on both the Huracan Performante and Aventador SVJ. The glossy shine of this color makes Nero accents the primary choice. ",
    "hex_color": "#C10001",
    "hex_text": "#C10001",
    "rgb_text": "rgb(193,0,1)",
    "cmyk_text": "0, 100, 99, 24",
    "ral_text": "RAL 3020",
    "related_color_1": "Rosso Leto ",
    "related_color_2": "Rosso Leto ",
    "related_color_3": "Rosso Efesto"
  },
  {
    "_id": 61,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Rosso Leto ",
    "short_description": "Lamborghini's Ad Personam deep red color.",
    "long_description": "Rosso Leto gives Aventadors a powerful and classic look with its deep red color. Black and silver accents compliment this color beautifully.",
    "hex_color": "#B60035",
    "hex_text": "#B60035",
    "rgb_text": "rgb(182,0,53)",
    "cmyk_text": "0, 100, 71, 29",
    "ral_text": "RAL 3027",
    "related_color_1": "Rosso Bia",
    "related_color_2": "Rosso Leto ",
    "related_color_3": "Rosso Arancio"
  },
  {
    "_id": 62,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Ermes",
    "short_description": "Lamborghini's Ad Personam dark green color.",
    "long_description": "Verde Ermes, found on both the Huracan and Aventador, is a dark green with a glossy shine. Although Nero accents are the most common and enhance this color the best, sublte red or yellow accents also pair beautifully with this color.",
    "hex_color": "#546E51",
    "hex_text": "#546E51",
    "rgb_text": "rgb(84,110,81)",
    "cmyk_text": "24, 0, 26, 57",
    "ral_text": "RAL 6010",
    "related_color_1": "Verde Ithaca",
    "related_color_2": "Verde Mantis",
    "related_color_3": "Verde Citrea"
  },
  {
    "_id": 63,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Verde Ithaca",
    "short_description": "Lamborghini's Ad Personam bright green color.",
    "long_description": "Verde Ithaca is a bright, neon green that gives Aventadors a bold and confident look. Nero accents compliments this color the best and accetuates the build of the car very well.",
    "hex_color": "#AEFF7E",
    "hex_text": "#AEFF7E",
    "rgb_text": "rgb(174,255,126)",
    "cmyk_text": "32, 0, 51, 0",
    "ral_text": "RAL 6019",
    "related_color_1": "Verde Ermes",
    "related_color_2": "Verde Scandal",
    "related_color_3": "Verde Metallic"
  },
  {
    "_id": 64,
    "_type": "Colors",
    "brand_type": "Lamborghini",
    "color_name": "Viola Aletheia",
    "short_description": "Lamborghini's Ad Personam deep purple color. ",
    "long_description": "Viola Aletheia can be found on the Aventador SVJ and is a stunning deep purple. Its glossy shine makes the color radiate in the sun, making it truly eye-catching. Bronze accents offer a unique compliment to this color, along with black accents.",
    "hex_color": "#492AC5",
    "hex_text": "#492AC5",
    "rgb_text": "rgb(73,42,197)\n",
    "cmyk_text": "63, 79, 0, 23",
    "ral_text": "RAL 5008",
    "related_color_1": "Viola Pasifae",
    "related_color_2": "Viola 30",
    "related_color_3": "Lantana Purple"
  },
  {
    "_id": 65,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso Scuderia",
    "short_description": "Ferrari's bright red color. ",
    "long_description": "Rosso Scuderia is a brighter Ferrari red that was first debuted on the F430. It is a versatile red that can be paired well with black, silver and white accents.",
    "hex_color": "        #ff2800",
    "hex_text": "        #ff2800",
    "rgb_text": "rgb(255,40,0)",
    "cmyk_text": "0, 84, 100, 0",
    "ral_text": "RAL 3024",
    "related_color_1": "Rosso Corsa",
    "related_color_2": "Rosso Fuoco",
    "related_color_3": "Rosso Mugello"
  },
  {
    "_id": 66,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso Corsa",
    "short_description": "Ferrari's classic red color.",
    "long_description": "Rosso Corsa is the classic red option that you can select. It has been seen as a classic since the F458, and can be optioned on every car model like the 488, 812 Superfast, LaFerrari and more. It is mostly seen paired with black and silver, but can work with more bold accents like yellow as well. ",
    "hex_color": "#D40000",
    "hex_text": "#D40000",
    "rgb_text": "rgb(212,0,0)",
    "cmyk_text": "0, 100, 100, 17",
    "ral_text": "RAL 3028",
    "related_color_1": "Rosso Scuderia",
    "related_color_2": "Rosso 70 Anni",
    "related_color_3": "Rosso Dino"
  },
  {
    "_id": 67,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso Mugello",
    "short_description": "Ferrari's dark red color.",
    "long_description": "Rosso Mugello is Ferrari's deep, almost maroon red. It is a color that's been seen as far back as the 599 GTO and F430, as well as on special models like the Monza SP. This deep red looks almost stealthy, and pairs well with either Silver or Gold accents. ",
    "hex_color": "#7A212A",
    "hex_text": "#7A212A",
    "rgb_text": "rgb(122,33,42)",
    "cmyk_text": "0, 73, 66, 52",
    "ral_text": "RAL 3032",
    "related_color_1": "Rosso Dino",
    "related_color_2": "Rosso Fiorano",
    "related_color_3": "Rosso Corsa"
  },
  {
    "_id": 68,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso Fuoco",
    "short_description": "Ferrari's triple layer red color.",
    "long_description": "Rosso Fuoco is a beautiful triple layer red paint that is a popular LaFerrari color. The triple layer nature of it makes it shimmer in the sunlight, and accentuates the special curves and lines of any Ferrari. ",
    "hex_color": "#D13442",
    "hex_text": "#D13442",
    "rgb_text": "rgb(209,52,66)",
    "cmyk_text": "0, 75, 68, 18",
    "ral_text": "RAL 3018",
    "related_color_1": "Rosso Mugello",
    "related_color_2": "Rosso Corsa",
    "related_color_3": "Rosso Fiorano"
  },
  {
    "_id": 69,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso Dino",
    "short_description": "Ferrari's red/orange color.",
    "long_description": "Rosso Dino is a red Ferrari paint color that verges almost on orange. It looks like the sunset, and has been seen on all models as far back as the Ferrari Enzo. It is paired best with silver, black, or gold accents due to its bright nature. ",
    "hex_color": "#FC652E",
    "hex_text": "#FC652E",
    "rgb_text": "rgb(252,101,46)",
    "cmyk_text": "0, 60, 82, 1",
    "ral_text": "RAL 2008",
    "related_color_1": "Rosso Fiorano",
    "related_color_2": "Rosso Fuoco",
    "related_color_3": "Rosso Mugello"
  },
  {
    "_id": 70,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso Fiorano",
    "short_description": "Ferrari's ruby red color.",
    "long_description": "Rosso Fiorano is a darker metallic red that looks similar to Fuoco. It has been seen on Pistas all the way to the 599 GTO, and is a more subtle red color. This color pairs best with black, or bright silver colors that give a contrast. ",
    "hex_color": "#5D0001",
    "hex_text": "#5D0001",
    "rgb_text": "rgb(93,0,1)",
    "cmyk_text": "0, 100, 99, 64",
    "ral_text": "RAL 3004",
    "related_color_1": "Rosso Dino",
    "related_color_2": "Rosso 70 Anni",
    "related_color_3": "Rosso Fuoco"
  },
  {
    "_id": 71,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Rosso 70 Anni",
    "short_description": "Ferrari's 70th anniversary celebration color.",
    "long_description": "Ferrari's 70th anniversario color is an homage to their most prominent color. It looks similar to Rosso Corsa, but pops a bit less in the sunlight. This color is best if you're looking to bring history to your modern Ferrari, and is primarily seen on the 812 Superfast. ",
    "hex_color": "#C40C19",
    "hex_text": "#C40C19",
    "rgb_text": "rgb(196,12,25)\n",
    "cmyk_text": "0, 94, 87, 23",
    "ral_text": "RAL 3020",
    "related_color_1": "Rosso Fiorano",
    "related_color_2": "Rosso Corsa",
    "related_color_3": "Rosso Scuderia"
  },
  {
    "_id": 72,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Giallo Modena",
    "short_description": "Ferrari's triple layer yellow color.",
    "long_description": "Giallo Modena is Ferrari's classic triple yellow paint that has been seen on models as early as the F40. This bright yellow pops in the suns, and outlines Ferrari's specific angles well. It is best paired with bright silver accents. ",
    "hex_color": "#FCE903",
    "hex_text": "#FCE903",
    "rgb_text": "rgb(252,233,3)",
    "cmyk_text": "0, 8, 99, 1",
    "ral_text": "RAL 1016",
    "related_color_1": "Giallo Tenerife",
    "related_color_2": "Racing Yellow",
    "related_color_3": "Giallo Inti"
  },
  {
    "_id": 73,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Grigio Ingrid",
    "short_description": "Ferrari's beige grey color.",
    "long_description": "Grigio Ingrid, although classified as grey, is a more champagne hue that highlights the classiness of a Ferrari. It is a rare color choice, but is seen on cars as early as the 612 Scaglietti. This color pairs best with a classy specification of silver accents. ",
    "hex_color": "#756D62",
    "hex_text": "#756D62",
    "rgb_text": "rgb(117,109,98)",
    "cmyk_text": "0, 7, 16, 54",
    "ral_text": "RAL 7006",
    "related_color_1": "Grigio Alloy",
    "related_color_2": "Grigio Silverstone",
    "related_color_3": "Grigio Titanio"
  },
  {
    "_id": 74,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Grigio Alloy",
    "short_description": "Ferrari's light grey (blue) color.",
    "long_description": "Grigio Alloy is a extremely light grey hue that has blue undertons in the sun. This color has a beautiful reflection, and pops in the sun. It has been seen on the F458, as well as earlier and later models. It is commonly paired with black accents fro a stealthy look, or silver for a classy asthetic. ",
    "hex_color": "#A3C7E9",
    "hex_text": "#A3C7E9",
    "rgb_text": "rgb(163,199,233)",
    "cmyk_text": "30, 15, 0, 9",
    "ral_text": "RAL 7047",
    "related_color_1": "Grigio Silverstone",
    "related_color_2": "Grigio Ingrid",
    "related_color_3": "Grigio Ferro"
  },
  {
    "_id": 75,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Grigio Titanio",
    "short_description": "Ferrari's classic grey color.",
    "long_description": "Grigio Titanio is a classic Ferrari grey that gives the car a different look than the traditional bright colors. It has been seen on all modern Ferrari models like the F8, 812, and even the Roma. This is a more stealthy Ferrari, so it pairs well with either black or silver accents. ",
    "hex_color": "#A8B8C0",
    "hex_text": "#A8B8C0",
    "rgb_text": "rgb(168,184,192)",
    "cmyk_text": "13, 4, 0, 25",
    "ral_text": "RAL 7040",
    "related_color_1": "Grigio Ingrid",
    "related_color_2": "Grigio Alloy",
    "related_color_3": "Grigio Ferro"
  },
  {
    "_id": 76,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Grigio Silverstone",
    "short_description": "Ferrari's dark grey color.",
    "long_description": "Grigio Silverstone is a stealthy dark grey hue that makes Ferraris look menacing. It has been as early as the 458 Speciale, and looks stunning with yellow accents that help enhance the Ferrari fender shield. ",
    "hex_color": "#585C64",
    "hex_text": "#585C64",
    "rgb_text": "rgb(88,92,100)",
    "cmyk_text": "12, 8, 0, 61",
    "ral_text": "RAL 7015",
    "related_color_1": "Grigio Titanio",
    "related_color_2": "Grigio Ingrid",
    "related_color_3": "Grigio Ferro"
  },
  {
    "_id": 77,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Grigio Ferro",
    "short_description": "Ferrari's light grey color.",
    "long_description": "Grigio Ferro is a lighter grey that has shines in the sun. It also has reflective qualities, and pairs well with Silver, Black or Yellow accents. ",
    "hex_color": "#626062",
    "hex_text": "#626062",
    "rgb_text": "rgb(98,96,98)",
    "cmyk_text": "0, 2, 0, 62",
    "ral_text": "RAL 7012",
    "related_color_1": "Grigio Scuro",
    "related_color_2": "Grigio Titanio",
    "related_color_3": "Grigio Alloy"
  },
  {
    "_id": 78,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Grigio Scuro",
    "short_description": "Ferrari's deep grey color.",
    "long_description": "Grigio Scuro almost has triple-layer grey qualities because it is a very deep, bold grey. This color pairs best with black accents to accentuate the stealthy nature of the color, and is seen commonly on the mid-engine Ferraris like the F458 and F488. ",
    "hex_color": "#4C4E4D",
    "hex_text": "#4C4E4D",
    "rgb_text": "rgb(76,78,77)",
    "cmyk_text": "3, 0, 1, 69",
    "ral_text": "RAL 7043",
    "related_color_1": "Grigio Ferro",
    "related_color_2": "Grigio Ferro",
    "related_color_3": "Grigio Alloy"
  },
  {
    "_id": 79,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Blu Scozia",
    "short_description": "Ferrari's dark blue color.",
    "long_description": "Blu Scozia is one of the most elegant blue Ferrari colors. It is a darker blue, but shines a bit in the sun. This color is very versatile, pairing well with gold, silver, and black, and is seen on the F488 and F12 Berlinetta. ",
    "hex_color": "#505C77",
    "hex_text": "#505C77",
    "rgb_text": "rgb(80,92,119)",
    "cmyk_text": "33, 23, 0, 53",
    "ral_text": "RAL 5000",
    "related_color_1": "Blu Swaters",
    "related_color_2": "Blu Tour De France",
    "related_color_3": "Blu Abu Dhabi"
  },
  {
    "_id": 80,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Blu Swaters",
    "short_description": "Ferrari's royal blue color.",
    "long_description": "Blu Swaters is a royal Ferrari blue has triple-layer paint qualities. This stunning color looks both stealthy and elegant, and is most commonly seen on the 812 Superfast. It is best paired with black accents. ",
    "hex_color": "#163166",
    "hex_text": "#163166",
    "rgb_text": "rgb(22,49,102)",
    "cmyk_text": "78, 52, 0, 60",
    "ral_text": "RAL 5022",
    "related_color_1": "Blu Scozia",
    "related_color_2": "Blu Abu Dhabi",
    "related_color_3": "Blu Swaters"
  },
  {
    "_id": 81,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Bianco Avus",
    "short_description": "Ferrari's classic white color.",
    "long_description": "Bianco Avus is Ferrari's classic white color that is most commonly specified on the F488 and F12. It is a pearly white that makes the Ferrari look elegant, and can be paired with virtually any accent color. ",
    "hex_color": "#F2F3F6",
    "hex_text": "#F2F3F6",
    "rgb_text": "rgb(242,243,246)",
    "cmyk_text": "2, 1, 0, 4",
    "ral_text": "RAL 9003",
    "related_color_1": "Bianco Avorio",
    "related_color_2": "Bianco Monocerus",
    "related_color_3": "Pearl White"
  },
  {
    "_id": 82,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Blu Pozzi",
    "short_description": "Ferrari's deep blue color.",
    "long_description": "Blu Pozzi is a very dark blue that looks almost black from certain angles. It is a great color choice if you want to bring a bit of pop to the color beyond black, and pairs well with grey accents. ",
    "hex_color": "#2C3970",
    "hex_text": "#2C3970",
    "rgb_text": "rgb(44,57,112)",
    "cmyk_text": "61, 49, 0, 56",
    "ral_text": "RAL 5022",
    "related_color_1": "Blu Abu Dhabi",
    "related_color_2": "Blu Tour De France",
    "related_color_3": "Blu Scozia"
  },
  {
    "_id": 83,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Blu Abu Dhabi",
    "short_description": "Ferrari's light blue color.",
    "long_description": "Blu Abu Dhabi is a brighter royal blue that shines in the sun. It is best paired with white accents, and has an elegance that represents the Ferrari brand well.  ",
    "hex_color": "#2885B5",
    "hex_text": "#2885B5",
    "rgb_text": "rgb(40,133,181)",
    "cmyk_text": "78, 27, 0, 29",
    "ral_text": "RAL 5012",
    "related_color_1": "Blu Pozzi",
    "related_color_2": "Blu Swaters",
    "related_color_3": "Blu Tour De France"
  },
  {
    "_id": 84,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Blu Tour De France",
    "short_description": "Ferrari's classic blue color.",
    "long_description": "Blu Tour de France is a lighter classic blue that is commonly seen on the F458, and 812 Superfast. It is best paired with silver, or black accents. ",
    "hex_color": "#2243AA",
    "hex_text": "#2243AA",
    "rgb_text": "rgb(34,67,170)",
    "cmyk_text": "80, 61, 0, 33",
    "ral_text": "RAL 5002",
    "related_color_1": "Blu Scozia",
    "related_color_2": "Blu Swaters",
    "related_color_3": "Blu Pozzi"
  },
  {
    "_id": 85,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Argento Nurburgring",
    "short_description": "Ferrari's metallic silver color.",
    "long_description": "Argento Nurburgring is a light silver Ferrari color that has is commonly seen on front-mid engine Ferrari liks the California, F12, or 812 Superfast. It is a bright silver color, and can look stealthy with black accents. ",
    "hex_color": "#CACBCE",
    "hex_text": "#CACBCE",
    "rgb_text": "rgb(202,203,206)",
    "cmyk_text": "2, 1, 0, 19",
    "ral_text": "RAL 7047",
    "related_color_1": "Ice Silver",
    "related_color_2": "Dolomite Silver Metallic",
    "related_color_3": "GT Silver Metallic"
  },
  {
    "_id": 86,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Nero Daytona",
    "short_description": "Ferrari's classic black color.",
    "long_description": "Nero Daytona is a classic black that makes the Ferrari a bit less abrassive. This is a historical color that has been seen as far back as the F50, and looks best with black rims to make it even more subtle. ",
    "hex_color": "#231F1C",
    "hex_text": "#231F1C",
    "rgb_text": "rgb(35,31,28)",
    "cmyk_text": "0, 11, 20, 86",
    "ral_text": "RAL 8022",
    "related_color_1": "Nero Pegaso",
    "related_color_2": "Jet Black Metallic",
    "related_color_3": "Fire Black"
  },
  {
    "_id": 87,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Bianco Avorio",
    "short_description": "Ferrari's cream white color.",
    "long_description": "Bianco Avorio is a white cream color that has been seen on classic cars like the 599 GTO. It is a less common option now, making it more rare, and looks beautiful with silver accents. ",
    "hex_color": "#E5DEDC",
    "hex_text": "#E5DEDC",
    "rgb_text": "rgb(229,222,220)",
    "cmyk_text": "0, 3, 4, 10",
    "ral_text": "RAL 9003",
    "related_color_1": "Bianco Avus",
    "related_color_2": "Bianco Asopo",
    "related_color_3": "Bianco Comes"
  },
  {
    "_id": 88,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Canna Di Fucile",
    "short_description": "Ferrari's metallic grey color.",
    "long_description": "Canna Di Fucile is commonly compared to Grigio Silverstone, because of their metallic grey qualities. This Ferrari color looks incredible with yellow accents to compliment it. ",
    "hex_color": "#7E8792",
    "hex_text": "#7E8792",
    "rgb_text": "rgb(126,135,146)",
    "cmyk_text": "14, 8, 0, 43",
    "ral_text": "RAL 7046",
    "related_color_1": "Carbon Black Metallic",
    "related_color_2": "Graphite Metallic",
    "related_color_3": "Grigio Antares"
  },
  {
    "_id": 89,
    "_type": "Colors",
    "brand_type": "Ferrari",
    "color_name": "Verde British",
    "short_description": "Ferrari's British racing green color.",
    "long_description": "Like the name suggests, Verde British is Ferrari's British racing green color. This darker moss green has been historically seen across all car brands, and looks best with silver accents. ",
    "hex_color": "#004225",
    "hex_text": "#004225",
    "rgb_text": "rgb(0,66,37)",
    "cmyk_text": "100, 0, 44, 74",
    "ral_text": "RAL 6035",
    "related_color_1": "Verde Selvans",
    "related_color_2": "Racing Green",
    "related_color_3": "Verde Metallic"
  },
  {
    "_id": 90,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Aventurine Green Metallic",
    "short_description": "Porsche's metallic dark green color.",
    "long_description": "Aventurine Green Metallic is a dark green with grey undertones that give the color a metallic look. It can be found primarily on the 911 and looks stunning with silver or gold accents as well as subtle red accents.",
    "hex_color": "#605E51",
    "hex_text": "#605E51",
    "rgb_text": "rgb(96,94,81)",
    "cmyk_text": "0, 2, 16, 62",
    "ral_text": "RAL 7009",
    "related_color_1": "Python Green",
    "related_color_2": "Jade Green",
    "related_color_3": "Viper Green"
  },
  {
    "_id": 91,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Python Green",
    "short_description": "Porsche's bright green color.",
    "long_description": "Python Green is a bright green that's found on both the 911 and Cayman. This color gives off a radiant and glossy finish and pairs well with black, silver and white accents.",
    "hex_color": "#1FF497",
    "hex_text": "#1FF497",
    "rgb_text": "rgb(31,244,151)",
    "cmyk_text": "87, 0, 38, 4",
    "ral_text": "RAL 6038",
    "related_color_1": "Emerald Green Metallic",
    "related_color_2": "Acid Green",
    "related_color_3": "Viper Green"
  },
  {
    "_id": 92,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Jade Green",
    "short_description": "Porsche's bright teal color.",
    "long_description": "Jade green is a traditional Porsche Color that has been as far back as the early 1970s 911. It is a bright teal color that stands out best with silver, or black accents. ",
    "hex_color": "#00BC96",
    "hex_text": "#00BC96",
    "rgb_text": "rgb(0,188,150)",
    "cmyk_text": "100, 0, 20, 26",
    "ral_text": "RAL 6027",
    "related_color_1": "Aventurine Green Metallic",
    "related_color_2": "Acid Green",
    "related_color_3": "Viper Green"
  },
  {
    "_id": 93,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Acid Green",
    "short_description": "Porsche's electric green color.",
    "long_description": "Acid Green is a shocking electric green that made its debut on the 918 but can also now be found on the 911. Black and subtle gold accents compliment this color beautifully to accentuate the exotic look.",
    "hex_color": "#CBE800",
    "hex_text": "#CBE800",
    "rgb_text": "rgb(203,232,0)",
    "cmyk_text": "13, 0, 100, 9",
    "ral_text": "RAL 1016",
    "related_color_1": "Emerald Green Metallic",
    "related_color_2": "Jade Green",
    "related_color_3": "Viper Green"
  },
  {
    "_id": 94,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Viper Green",
    "short_description": "Porsche's classic green color.",
    "long_description": "Viper Green is a historical Porsche color that has been seen as far back as the older 911s. It is still a common spec color for the 911s because of its heritage, and pairs best with silver, black or yellow accents.",
    "hex_color": "#029220",
    "hex_text": "#029220",
    "rgb_text": "rgb(2,146,32)",
    "cmyk_text": "99, 0, 78, 43",
    "ral_text": "RAL 6037",
    "related_color_1": "Aventurine Green Metallic",
    "related_color_2": "Viper Green",
    "related_color_3": "Emerald Green Metallic"
  },
  {
    "_id": 95,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Emerald Green Metallic",
    "short_description": "Porsche's British racing green color.",
    "long_description": "Emerald Green is a darker racing green color that has been seen on historical Porsches as far back as the 70s. It is still a beautiful spec choice to pick as a homage to the historical racing days, and pairs best with black accents.",
    "hex_color": "#328983",
    "hex_text": "#328983",
    "rgb_text": "rgb(50,137,131)",
    "cmyk_text": "64, 0, 4, 46",
    "ral_text": "RAL 6033",
    "related_color_1": "Acid Green",
    "related_color_2": "Jade Green",
    "related_color_3": "Aventurine Green Metallic"
  },
  {
    "_id": 96,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Jet Black Metallic",
    "short_description": "Porsche's metallic black color.",
    "long_description": "Jet Black Metallic is a classic dark black color that has been seen on all Porsche variations from the Taycans to Macans and Cayennes. It is the best choice for a stealthy specification, and can be paired with any accent color choice. ",
    "hex_color": "#201A1E",
    "hex_text": "#201A1E",
    "rgb_text": "rgb(32,26,30)",
    "cmyk_text": "0, 19, 6, 87",
    "ral_text": "RAL 8022",
    "related_color_1": "Carbon Black Metallic",
    "related_color_2": "Nero Helene",
    "related_color_3": "Nero Daytona"
  },
  {
    "_id": 97,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Carbon Black Metallic",
    "short_description": "Porsche's bright metallic black color.",
    "long_description": "Carbon Black Metallic can be found on the 911 and is a bright, metallic black. The glossy shine of this color is truly eye-catching and looks stunning with silver, gold or yellow accents.",
    "hex_color": "#74828B",
    "hex_text": "#74828B",
    "rgb_text": "rgb(116,130,139)\n",
    "cmyk_text": "17, 6, 0, 45",
    "ral_text": "RAL 7000",
    "related_color_1": "Jet Black Metallic",
    "related_color_2": "Sapphire Black",
    "related_color_3": "Nero Nemesis"
  },
  {
    "_id": 98,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Racing Yellow",
    "short_description": "Porsche's classic yellow color.",
    "long_description": "Racing Yellow is a classic, bright yellow that brings a confident pop of color to the car. Found on the 911, this color is accentuated by black or silver accents.",
    "hex_color": "#F8CD02",
    "hex_text": "#F8CD02",
    "rgb_text": "rgb(248,205,2)",
    "cmyk_text": "0, 17, 99, 3",
    "ral_text": "RAL 1018",
    "related_color_1": "Giallo Orion",
    "related_color_2": "Giallo Modena",
    "related_color_3": "Oros Elios"
  },
  {
    "_id": 99,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Guards Red",
    "short_description": "Porsche's classic red color.",
    "long_description": "Guards Red is found primarily on the 911 and is a beautiful classic red that gives the car a shiny and glossy look. Black and silver accents pair best with this color, along with a subtle yellow.",
    "hex_color": "#FA2223",
    "hex_text": "#FA2223",
    "rgb_text": "rgb(250,34,35)",
    "cmyk_text": "0, 86, 86, 2",
    "ral_text": "RAL 3024",
    "related_color_1": "Rosso Corsa",
    "related_color_2": "Polo Red",
    "related_color_3": "Arancio Argos"
  },
  {
    "_id": 100,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Carmine Red",
    "short_description": "Porsche's deep red color.",
    "long_description": "Carmine Red is a shiny, deep red that gives the car a classy look. It can be found on all Porsche models and is paired well with black, silver and yellow accents.",
    "hex_color": "#9D0620",
    "hex_text": "#9D0620",
    "rgb_text": "rgb(157,6,32)",
    "cmyk_text": "0, 96, 80, 38",
    "ral_text": "RAL 3002",
    "related_color_1": "Rosso Fuoco",
    "related_color_2": "Volcano Red",
    "related_color_3": "Rosso Bia"
  },
  {
    "_id": 101,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Scarlet Red",
    "short_description": "Porsche's red/orange color.",
    "long_description": "Scarlet Red is a traditional Porsche color that has been seen on cars as far back as the 1970s Porsche 914. It is a classic red that looks orange in the sunlight, and is paired best with black or silver accents.",
    "hex_color": "#F82100",
    "hex_text": "#F82100",
    "rgb_text": "rgb(248,33,0)",
    "cmyk_text": "0, 87, 100, 3",
    "ral_text": "RAL 2004",
    "related_color_1": "Rosso Arancio",
    "related_color_2": "Rosso Scuderia",
    "related_color_3": "Red Metallic"
  },
  {
    "_id": 102,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Polo Red",
    "short_description": "Porsche's classic red color.",
    "long_description": "Polo Red is a classic darker red Porsche color that has been as far back as the 1960s Porsche 911s. It is a beautiful homage to the brand's history, and is paired best with silver accents. ",
    "hex_color": "#980611",
    "hex_text": "#980611",
    "rgb_text": "rgb(152,6,17)",
    "cmyk_text": "0, 96, 89, 40",
    "ral_text": "RAL 3002",
    "related_color_1": "Rosso Mugello",
    "related_color_2": "Mercury Red",
    "related_color_3": "Scarlet Red"
  },
  {
    "_id": 103,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Red Metallic",
    "short_description": "Porsche's metallic red color.",
    "long_description": "Red Metallic gives off a daring look with its dark, metallic red color and can be found primarily on the 911. Black and silver accents compliment this color beautifully. ",
    "hex_color": "#A72241",
    "hex_text": "#A72241",
    "rgb_text": "rgb(167,34,65)",
    "cmyk_text": "0, 80, 61, 35",
    "ral_text": "RAL 3027",
    "related_color_1": "Rosso Efesto",
    "related_color_2": "Rosso Dino",
    "related_color_3": "Guards Red"
  },
  {
    "_id": 104,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Rubystone Red",
    "short_description": "Porsche's pink ruby color.",
    "long_description": "Rubystone Red made its debut on the old Porsche 964 and can now be found on the 911 and Carrera. This bright, fuchsia pink accentuates the sleek nature of hte car and pairs well with black and silver accents.",
    "hex_color": "#F3037E",
    "hex_text": "#F3037E",
    "rgb_text": "rgb(243,3,126)",
    "cmyk_text": "0, 99, 48, 5",
    "ral_text": "RAL 4010",
    "related_color_1": "Scarlet Red",
    "related_color_2": "Carmine Red",
    "related_color_3": "Rosso Scuderia"
  },
  {
    "_id": 105,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Agate Grey Metallic",
    "short_description": "Porsche's metallic grey color.",
    "long_description": "Agate Grey Metallic can be found on the 911 and is a dark, metallic grey. Its sleek and stealthy look is complimented well with black and yellow accents. ",
    "hex_color": "#AAB1B9",
    "hex_text": "#AAB1B9",
    "rgb_text": "rgb(170,177,185)",
    "cmyk_text": "8, 4, 0, 27",
    "ral_text": "RAL 7040",
    "related_color_1": "Chalk",
    "related_color_2": "Graphite Grey",
    "related_color_3": "Graphite Metallic"
  },
  {
    "_id": 106,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Chalk",
    "short_description": "Porsche's light grey color.",
    "long_description": "Chalk is a pearlescent, light grey that gives the 911 a radiant and polished look. This versatile color pairs well with many accent colors including black, yellow and red.",
    "hex_color": "#A5A4AC",
    "hex_text": "#A5A4AC",
    "rgb_text": "rgb(165,164,172)",
    "cmyk_text": "4, 5, 0, 33",
    "ral_text": "RAL 7004",
    "related_color_1": "Agate Grey Metallic",
    "related_color_2": "Graphite Grey",
    "related_color_3": "Graphite Metallic"
  },
  {
    "_id": 107,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Graphite Grey",
    "short_description": "Porsche's classic grey color.",
    "long_description": "Graphite Grey can be found on the 911 and is a classic grey that gives the car a glossy and polished look. Black and silver accents compliment this color beautifully.",
    "hex_color": "#748795",
    "hex_text": "#748795",
    "rgb_text": "rgb(116,135,149)",
    "cmyk_text": "22, 9, 0, 42",
    "ral_text": "RAL 7000",
    "related_color_1": "Chalk",
    "related_color_2": "Agate Grey Metallic",
    "related_color_3": "Graphite Metallic"
  },
  {
    "_id": 108,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Graphite Metallic",
    "short_description": "Porsche's bright grey color.",
    "long_description": "Graphite Metallic is a bright grey with subtle blue undertones that can be found on the 911. Black and silver accents work well to complete this classy look.",
    "hex_color": "#546A78",
    "hex_text": "#546A78",
    "rgb_text": "rgb(84,106,120)",
    "cmyk_text": "30, 12, 0, 53",
    "ral_text": "RAL 7031",
    "related_color_1": "Chalk",
    "related_color_2": "Agate Grey Metallic",
    "related_color_3": "Graphite Grey"
  },
  {
    "_id": 109,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Sand Beige",
    "short_description": "Porsche's flat beige color.",
    "long_description": "Sand beige is a traditional color that has been found on Porsches as far back as the 1960s like the 912 and even vintage 911s. It is a bright beige color that has a flat hue and pairs best with silver accents.",
    "hex_color": "#C9AC80",
    "hex_text": "#C9AC80",
    "rgb_text": "rgb(201,172,128)",
    "cmyk_text": "0, 14, 36, 21",
    "ral_text": "RAL 1001",
    "related_color_1": "Graphite Metallic",
    "related_color_2": "Agate Grey Metallic",
    "related_color_3": "Dolomite Silver Metallic"
  },
  {
    "_id": 110,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Dolomite Silver Metallic",
    "short_description": "Porsche's metallic silver color.",
    "long_description": "Dolomite Silver Metallic creates a sleek look with its metallic silver color. Primarily found on the 911, this color pairs well with black and red accents.",
    "hex_color": "#9FB1BC",
    "hex_text": "#9FB1BC",
    "rgb_text": "rgb(159,177,188)",
    "cmyk_text": "15, 6, 0, 26",
    "ral_text": "RAL 7040",
    "related_color_1": "Sand Beige",
    "related_color_2": "GT Silver Metallic",
    "related_color_3": "Night Blue Metallic"
  },
  {
    "_id": 111,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "GT Silver Metallic",
    "short_description": "Porsche's light metallic grey color.",
    "long_description": "GT Silver Metallic, found primarily on the 911, is a light, metallic grey. This color is complimented well by black and red accents. ",
    "hex_color": "#A3ACB3",
    "hex_text": "#A3ACB3",
    "rgb_text": "rgb(163,172,179)",
    "cmyk_text": "9, 4, 0, 30",
    "ral_text": "RAL 7040",
    "related_color_1": "Ice Blue Metallic",
    "related_color_2": "Dolomite Silver Metallic",
    "related_color_3": "Metallic Blue"
  },
  {
    "_id": 112,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Gentian Blue Metallic",
    "short_description": "Porsche's metallic blue color.",
    "long_description": "Gentian Blue Metallic is deep, royal blue with a metallic sheen that gives the car a vibrant look. Found on the 911, this color looks stunning black and subtle red accents.",
    "hex_color": "#09203F",
    "hex_text": "#09203F",
    "rgb_text": "rgb(9,32,63)",
    "cmyk_text": "86, 49, 0, 75",
    "ral_text": "RAL 5013",
    "related_color_1": "Metallic Blue",
    "related_color_2": "GT Silver Metallic",
    "related_color_3": "Dolomite Silver Metallic"
  },
  {
    "_id": 113,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Night Blue Metallic",
    "short_description": "Porsche's dark metallic blue color.",
    "long_description": "Night Blue Metallic is a rich navy blue that creates a sleek and stealthy look on the 911. Red, black and silver accents compliment this color beautifully.",
    "hex_color": "#385D89",
    "hex_text": "#385D89",
    "rgb_text": "rgb(56,93,137)",
    "cmyk_text": "59, 32, 0, 46",
    "ral_text": "RAL 5023",
    "related_color_1": "Gentian Blue Metallic",
    "related_color_2": "Metallic Blue",
    "related_color_3": "Gentian Blue Metallic"
  },
  {
    "_id": 114,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Azure Blue",
    "short_description": "Porsche's classic blue color.",
    "long_description": "Azure Blue is one of Porsche's most classic blue colors. It has been seen on vintage 1950s Porsches like the 381, and has a flat blue hue. It pairs best with silver colors, and is no longer common.",
    "hex_color": "#3C566F",
    "hex_text": "#3C566F",
    "rgb_text": "rgb(60,86,111)",
    "cmyk_text": "46, 23, 0, 56",
    "ral_text": "RAL 5000",
    "related_color_1": "Miami Blue",
    "related_color_2": "Metallic Blue",
    "related_color_3": "Riviera Blue"
  },
  {
    "_id": 115,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Metallic Blue",
    "short_description": "Porsche's classic metallic blue color.",
    "long_description": "\nSapphire Blue Metallic is an electric, royal blue that can be found on both the Cayman and 911. This color creates an electric look that pairs well with black and silver accents . ",
    "hex_color": "#0387D9",
    "hex_text": "#0387D9",
    "rgb_text": "rgb(3,135,217)",
    "cmyk_text": "99, 38, 0, 15",
    "ral_text": "RAL 5012",
    "related_color_1": "Riviera Blue",
    "related_color_2": "Azure Blue",
    "related_color_3": "Arrow Blue"
  },
  {
    "_id": 116,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Ice Blue Metallic",
    "short_description": "Porsche's light metallic blue color.",
    "long_description": "Ice Blue Metallic can be found on the 911 and is a frosty, light blue with a metallic finish. To compliment this color, black and silver accents pair the best.",
    "hex_color": "#8C969F",
    "hex_text": "#8C969F",
    "rgb_text": "rgb(140,150,159)",
    "cmyk_text": "12, 6, 0, 38",
    "ral_text": "RAL 7001",
    "related_color_1": "Arrow Blue",
    "related_color_2": "Bahama Blue",
    "related_color_3": "Moonlight Blue Metallic"
  },
  {
    "_id": 117,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Bahama Blue",
    "short_description": "Porsche's bright metallic blue color.",
    "long_description": "Bahama Blue is a bright metallic blue color that has been seen on vintage 911 cars from the 1970s. It pairs best with silver accents.",
    "hex_color": "#2971EA",
    "hex_text": "#2971EA",
    "rgb_text": "rgb(41,113,234)",
    "cmyk_text": "82, 52, 0, 8",
    "ral_text": "RAL 5023",
    "related_color_1": "Metallic Blue",
    "related_color_2": "Arrow Blue",
    "related_color_3": "Miami Blue"
  },
  {
    "_id": 118,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Arrow Blue",
    "short_description": "Porsche's bright blue color.",
    "long_description": "Arrow Blue made its debut on the classic 911s and can now be found all modern day Porsches. This bright blue gives the car a bold and glossy look, and is accentuated by black silver, and subtle yellow accents.",
    "hex_color": "#0459DA",
    "hex_text": "#0459DA",
    "rgb_text": "rgb(4,89,218)",
    "cmyk_text": "98, 59, 0, 15",
    "ral_text": "RAL 5023",
    "related_color_1": "Miami Blue",
    "related_color_2": "Riviera Blue",
    "related_color_3": "Bahama Blue"
  },
  {
    "_id": 119,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Pastel blue",
    "short_description": "Porsche's light pastel blue color.",
    "long_description": "Pastel blue is a vintage bright blue color that was first seen in the early 1970s. It is often seen with white or silver accents.",
    "hex_color": "#A0D8FB",
    "hex_text": "#A0D8FB",
    "rgb_text": "rgb(160,216,251)",
    "cmyk_text": "36, 14, 0, 2",
    "ral_text": "RAL 6027",
    "related_color_1": "Riviera Blue",
    "related_color_2": "Metallic Blue",
    "related_color_3": "Ice Blue Metallic"
  },
  {
    "_id": 120,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Miami Blue",
    "short_description": "Porsche's light blue color.",
    "long_description": "Miami Blue is a bright sky blue that creates a bold look and can be seen on both the 911 and Cayman. Black and silver accents pair well with this color.",
    "hex_color": "#00B5C8",
    "hex_text": "#00B5C8",
    "rgb_text": "rgb(0,181,200)",
    "cmyk_text": "100, 10, 0, 22",
    "ral_text": "RAL 6034",
    "related_color_1": "Bahama Blue",
    "related_color_2": "Pastel blue",
    "related_color_3": "Riviera Blue"
  },
  {
    "_id": 121,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Riviera Blue",
    "short_description": "Porsche's bright blue color.",
    "long_description": "Riviera Blue is an electric, bright blue that is found on the 911. Black and silver accents highlight the power of this color and compliment it well.",
    "hex_color": "#018ADA",
    "hex_text": "#018ADA",
    "rgb_text": "rgb(1,138,218)",
    "cmyk_text": "100, 37, 0, 15",
    "ral_text": "RAL 5012",
    "related_color_1": "Moonlight Blue Metallic",
    "related_color_2": "Bahama Blue",
    "related_color_3": "Arrow Blue"
  },
  {
    "_id": 122,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Moonlight Blue Metallic",
    "short_description": "Porsche's dark metallic blue color.",
    "long_description": "Moonlight Blue Metallic made its debut on the Cayenne and is a dark, navy blue. This stealthy, powerful look pairs well with silver accents.",
    "hex_color": "#153149",
    "hex_text": "#153149",
    "rgb_text": "rgb(21,49,73)",
    "cmyk_text": "71, 33, 0, 71",
    "ral_text": "RAL 5003",
    "related_color_1": "Riviera Blue",
    "related_color_2": "Arrow Blue",
    "related_color_3": "Pastel blue"
  },
  {
    "_id": 123,
    "_type": "Colors",
    "brand_type": "Porsche",
    "color_name": "Lava Orange",
    "short_description": "Porsche's classic orange color.",
    "long_description": "Lava Orange is a flaming, ruby orange found on the 911. The powerful look of this color is emphasized with black and silver accents.",
    "hex_color": "#FF2600",
    "hex_text": "#FF2600",
    "rgb_text": "rgb(255,38,0)",
    "cmyk_text": "0, 85, 100, 0",
    "ral_text": "RAL 3024",
    "related_color_1": "Scarlet Red",
    "related_color_2": "Arancio Argos",
    "related_color_3": "Arancio Borealis"
  },
  {
    "_id": 124,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "McLaren Argon",
    "short_description": "McLaren's classic dark grey color.",
    "long_description": "McLaren Argon is a deep grey color that brings out the stealthy nature of the cars. Originally seen on the 720s, the car shines in the sun and pairs well with black or silver accents. ",
    "hex_color": "#626876",
    "hex_text": "#626876",
    "rgb_text": "rgb(98,104,118)",
    "cmyk_text": "17, 12, 0, 54",
    "ral_text": "RAL 4012",
    "related_color_1": "Storm Grey",
    "related_color_2": "Ice Silver",
    "related_color_3": "Grigio Lynx"
  },
  {
    "_id": 125,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Lime Green",
    "short_description": "McLaren's bright green color.",
    "long_description": "Lime green is a light bright green paint color that has been seen primarily on the 720s, and 600LT. It is a bright color, so it pairs best with subtle black accents.",
    "hex_color": "#C2ED3E",
    "hex_text": "#C2ED3E",
    "rgb_text": "rgb(194,237,62)",
    "cmyk_text": "18, 0, 74, 7",
    "ral_text": "RAL 1016",
    "related_color_1": "Racing Green",
    "related_color_2": "Mantis Green",
    "related_color_3": "Verde Selvans"
  },
  {
    "_id": 126,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Pearl White",
    "short_description": "McLaren's flat white color.",
    "long_description": "Pearl white is a bright triple layer white that was first seen on the McLaren P1. It brings out the elegance of McLarens, and can be paired with any accent color. ",
    "hex_color": "#EBEBEB",
    "hex_text": "#EBEBEB",
    "rgb_text": "rgb(235,235,235)",
    "cmyk_text": "0, 0, 0, 8",
    "ral_text": "RAL 9003",
    "related_color_1": "Bianco Monocerus",
    "related_color_2": "Bianco Avus",
    "related_color_3": "Bianco Isi"
  },
  {
    "_id": 127,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Racing Green",
    "short_description": "McLaren's British racing green color.",
    "long_description": "Racing Green is McLaren's version of the classic dark British Racing Green color. This historical color is a dark green that has a moss hue, and has been seen primarily on the Senna.",
    "hex_color": "#2F473A",
    "hex_text": "#2F473A",
    "rgb_text": "rgb(47,71,58)",
    "cmyk_text": "34, 0, 18, 72",
    "ral_text": "RAL 6028",
    "related_color_1": "Mantis Green",
    "related_color_2": "Lime Green",
    "related_color_3": "Verde Metallic"
  },
  {
    "_id": 128,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Mclaren Orange",
    "short_description": "McLaren's classic orange color.",
    "long_description": "McLaren (or Tarocco Orange) has been McLaren's historical color, seen on Formula 1 cars, and classic cars like the P1. This deep volcanic orange looks stunning with black accents, but also works well with silver accents. ",
    "hex_color": "#FFC43D",
    "hex_text": "#FFC43D",
    "rgb_text": "rgb(255,196,61)",
    "cmyk_text": "0, 23, 76, 0",
    "ral_text": "RAL 1018",
    "related_color_1": "Volcano Orange",
    "related_color_2": "Lava Orange",
    "related_color_3": "Arancio Bruciato"
  },
  {
    "_id": 129,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Storm Grey",
    "short_description": "McLaren's classic grey color.",
    "long_description": "Storm grey is McLaren's darkest grey. It has an almost matte quality in the dark, but reflects in the light. It has been seen primarily on the 570s, and pairs well with orange, red or yellow accents. ",
    "hex_color": "#8C8D92",
    "hex_text": "#8C8D92",
    "rgb_text": "rgb(140,141,146)",
    "cmyk_text": "4, 3, 0, 43",
    "ral_text": "RAL 7045",
    "related_color_1": "Titanium Silver",
    "related_color_2": "Graphite Grey",
    "related_color_3": "Grigio Telesto"
  },
  {
    "_id": 130,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Aurora Blue",
    "short_description": "McLaren's deep blue color.",
    "long_description": "Aurora blue is a deep royal blue that has been seen primarily on the 720s. It looks beautiful with black, or constrasting yellow and orange accents. ",
    "hex_color": "#172375",
    "hex_text": "#172375",
    "rgb_text": "rgb(23,35,117)",
    "cmyk_text": "80, 70, 0, 54",
    "ral_text": "RAL 5022",
    "related_color_1": "Curacao Blue",
    "related_color_2": "Blu Swaters",
    "related_color_3": "Bahama Blue"
  },
  {
    "_id": 131,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Curacao Blue",
    "short_description": "McLaren's bright blue color.",
    "long_description": "Curacao Blue is McLaren's bright blue color. It looks almost teal in the sun, and has been seen primarily on the 570s. This blue pairs perfectly with orange or silver accents.  ",
    "hex_color": "#00B8EE",
    "hex_text": "#00B8EE",
    "rgb_text": "rgb(0,184,238)",
    "cmyk_text": "100, 23, 0, 7",
    "ral_text": "RAL 5024",
    "related_color_1": "Aurora Blue",
    "related_color_2": "Vegas Blue",
    "related_color_3": "Blu Nila"
  },
  {
    "_id": 132,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Lantana Purple",
    "short_description": "McLaren's deep purple color.",
    "long_description": "Lantana purple is a deep purple color that looks both stealthy and elegant. It has been seen on the 570s variations, as well as the 720s variations, and is a common purple color choice. This purple pairs well with orange, yellow, silver or black accents.     ",
    "hex_color": "#351175",
    "hex_text": "#351175",
    "rgb_text": "rgb(53,17,117)",
    "cmyk_text": "55, 85, 0, 54",
    "ral_text": "RAL 5022",
    "related_color_1": "Cobalt Violet",
    "related_color_2": "Viola Aletheia",
    "related_color_3": "Viola Pasifae"
  },
  {
    "_id": 133,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Sapphire Black",
    "short_description": "McLaren's classic black color.",
    "long_description": "Sapphie Black is a massic McLaren black that looks almost blue in the sun. It is the perfect stealth choice, and has been seen on all McLaren models dating back to the MP4-12C. This black is very versatile, and be paired with any accent color. ",
    "hex_color": "#29324E",
    "hex_text": "#29324E",
    "rgb_text": "rgb(41,50,78)",
    "cmyk_text": "47, 36, 0, 69",
    "ral_text": "RAL 5013",
    "related_color_1": "Fire Black",
    "related_color_2": "Jet Black Metallic",
    "related_color_3": "Nero Pegaso"
  },
  {
    "_id": 134,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Ice Silver",
    "short_description": "McLaren's bright silver color.",
    "long_description": "Ice silver is a dark silver color that has been seen on all McLaren variations from the 570s all the way to the P1. It looks stunning with black accents, but can also be paired with red or orange contrasting colors. ",
    "hex_color": "#C4C8D4",
    "hex_text": "#C4C8D4",
    "rgb_text": "rgb(196,200,212)",
    "cmyk_text": "8, 6, 0, 17",
    "ral_text": "RAL 7047",
    "related_color_1": "Titanium Silver",
    "related_color_2": "Ice Blue Metallic",
    "related_color_3": "GT Silver Metallic"
  },
  {
    "_id": 135,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Titanium Silver",
    "short_description": "McLaren's classic silver color.",
    "long_description": "Titanium silver is a darker McLaren color that has a gun metal finish. It is a bit more stealthy than Ice Silver, and has been seen on cars as early as the MP4-12C. This silver is paired commonly with black, or orange accents. ",
    "hex_color": "#9BA2B4",
    "hex_text": "#9BA2B4",
    "rgb_text": "rgb(155,162,180)",
    "cmyk_text": "14, 10, 0, 29",
    "ral_text": "RAL 7040",
    "related_color_1": "Ice Silver ",
    "related_color_2": "Dolomite Silver Metallic",
    "related_color_3": "Grigio Silverstone"
  },
  {
    "_id": 136,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Mercury Red",
    "short_description": "McLaren's dark red color.",
    "long_description": "Mercury Red is a beautiful triple layer red dark red paint that is similar to Ferrari's Rosso Fuoco. It has been seen on cars as early as the MP4-12C and P1, and is a McLaren classic that pairs best with black accents. ",
    "hex_color": "#9B0E1F",
    "hex_text": "#9B0E1F",
    "rgb_text": "rgb(155,14,31)",
    "cmyk_text": "0, 91, 80, 39",
    "ral_text": "RAL 3002",
    "related_color_1": "Volcano Red",
    "related_color_2": "Rosso Mars",
    "related_color_3": "Scarlet Red"
  },
  {
    "_id": 137,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Volcano Red",
    "short_description": "McLaren's fire red color.",
    "long_description": "Volcano is McLaren's classic red color that was seen most commonly on the P1. It is a deep red color that shines brightly in the sun. This color pairs best with yellow or red accents. ",
    "hex_color": "#A80115",
    "hex_text": "#A80115",
    "rgb_text": "rgb(168,1,21)",
    "cmyk_text": "0, 99, 88, 34",
    "ral_text": "RAL 3002",
    "related_color_1": "Mercury Red",
    "related_color_2": "Guards Red",
    "related_color_3": "Rosso Bia"
  },
  {
    "_id": 138,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Cobalt Violet",
    "short_description": "McLaren's dark purple color.",
    "long_description": "Cobalt Purple is McLaren's darkest purple and can be mistaken for black in the dark. It is a stealthy color, and has been seen primarily on the 570s. This color pairs perfectly with bronze, black or silver accents. ",
    "hex_color": "#C8659E",
    "hex_text": "#C8659E",
    "rgb_text": "rgb(200,101,158)",
    "cmyk_text": "0, 50, 21, 22",
    "ral_text": "RAL 4003",
    "related_color_1": "Lantana Purple",
    "related_color_2": "Viola 30",
    "related_color_3": "Viola Pasifae"
  },
  {
    "_id": 139,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Volcano Orange",
    "short_description": "McLaren's fire orange color.",
    "long_description": "Volcano Orange is McLaren's classic P1 orange. It is a lighter triple-layer orange that was introduced on the P1, and pairs well with black accents. ",
    "hex_color": "#C82504",
    "hex_text": "#C82504",
    "rgb_text": "rgb(200,37,4)",
    "cmyk_text": "0, 82, 98, 22",
    "ral_text": "RAL 2002",
    "related_color_1": "McLaren Orange",
    "related_color_2": "Arancio Argos",
    "related_color_3": "Rosso Dino"
  },
  {
    "_id": 140,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Mantis Green",
    "short_description": "McLaren's bright green color.",
    "long_description": "Mantis green represents the ethos of a supercar perfectly: bright green. It was debuted on the 650S, and pairs well with both silver and black accents. ",
    "hex_color": "#63EA2E",
    "hex_text": "#63EA2E",
    "rgb_text": "rgb(99,234,46)",
    "cmyk_text": "58, 0, 80, 8",
    "ral_text": "RAL 6038",
    "related_color_1": "Lime Green",
    "related_color_2": "Racing Green",
    "related_color_3": "Viper Green"
  },
  {
    "_id": 141,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Fire Black",
    "short_description": "McLaren's metallic black color.",
    "long_description": "Fire black is a beautiful black color. Stealthy, but in direct sunlight shimmers with bright metallic flakes. It has been seen primarily on the P1, but other cars as back as the MP4-12C have also been seen in this color. This black can be paired with any accent color. ",
    "hex_color": "#191A1E",
    "hex_text": "#191A1E",
    "rgb_text": "rgb(25,26,30)",
    "cmyk_text": "17, 13, 0, 88",
    "ral_text": "RAL 8022",
    "related_color_1": "Sapphire Black",
    "related_color_2": "Nero Aldebaran",
    "related_color_3": "Nero Daytona"
  },
  {
    "_id": 142,
    "_type": "Colors",
    "brand_type": "McLaren",
    "color_name": "Vegas Blue",
    "short_description": "McLaren's classic blue color.",
    "long_description": "McLaren Blue is a classic blue color that has been seen primarily on the 570s variations. It pairs best with silver and black colors. ",
    "hex_color": "#0149D3",
    "hex_text": "#0149D3",
    "rgb_text": "rgb(1,73,211)",
    "cmyk_text": "100, 65, 0, 17",
    "ral_text": "RAL 5000",
    "related_color_1": "Aurora Blue",
    "related_color_2": "Curacao Blue",
    "related_color_3": "Azure Blue"
  },
  {
    "_id": 143,
    "_type": "Colors",
    "brand_type": "Audi",
    "color_name": "Nardo Grey",
    "short_description": "Audi's classic grey color.",
    "long_description": "Nardo grey is Audi's famous classic grey color. It is a darker grey that accentuates a cars lines in a stealthy way. It pairs best with red, black or orange accents. ",
    "hex_color": "#C0C6C8",
    "hex_text": "#C0C6C8",
    "rgb_text": "rgb(192,198,200)",
    "cmyk_text": "4, 1, 0, 22",
    "ral_text": "RAL 7035",
    "related_color_1": "Graphite Grey",
    "related_color_2": "Grigio Hati",
    "related_color_3": "Grigio Titanio"
  }
 ]


 for (const curr of data) {
  const currData = JSON.parse(JSON.stringify(curr));
  console.log(currData);
  client.create(currData);
 }





